# Generated by Django 5.2.1 on 2025-06-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(help_text="Введите email", max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
