# Generated by Django 5.2.1 on 2025-06-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name="Количество просмотров"),
        ),
    ]
