# Generated by Django 5.2.1 on 2025-06-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(max_length=50, verbose_name="Цена за покупку"),
        ),
    ]
